

services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd
      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks: [ elknet]
  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: dashboards
    environment: 
      - "OPENSEARCH_HOSTS=[\"htpp://opensearch:9200\"]"
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Str0ng!Passw0rd
    ports: 
      - "5601:5601"
    depends_on: [ opensearch ]
    networks: [ elknet ]
  logstash:
    build:
      context: .
      dockerfile: Dockerfile.logstash
    container_name: logstash
    ports: 
      - "5044:5044"
    volumes: 
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    depends_on: [ opensearch ]
    networks: [ elknet ]
networks:
  elknet:
    driver: bridge
      
      
